# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

# Command line
# Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
- task: CmdLine@2
  inputs:
    script: 'sudo chmod 777 Info' 
    #workingDirectory: # Optional
    #failOnStderr: false # Optional

- task: CmdLine@2
  inputs:
    script: 'sudo chmod 777 Info/test.html' 
    #workingDirectory: # Optional
    #failOnStderr: false # Optional


- task: CmdLine@2
  inputs:
    script: 'mkdir dell && touch dell/file1.txt' 
    #workingDirectory: # Optional
    #failOnStderr: false # Optional


- task: CmdLine@2
  inputs:
    script: 'sudo chmod 777 dell' 
    #workingDirectory: # Optional
    #failOnStderr: false # Optional


- task: CmdLine@2
  inputs:
    script: 'sudo chmod 777 dell/file1.txt' 
    #workingDirectory: # Optional
    #failOnStderr: false # Optional



- task: CmdLine@2
  inputs:
    script: 'ls -o'

# Copy files over SSH
# Copy files or build artifacts to a remote machine over SSH


    

  


