# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: CmdLine@2
  inputs:
    script: 'demo\vensim demo\Model\test.cmd'

- task: FtpUpload@2
  inputs:
    credentialsOption: 'inputs'
    serverUrl: 'ftp://104.215.23.24'
    username: 'test'
    password: 'test'
    rootDirectory: 'demo/Model/'
    filePatterns: '**'
    remoteDirectory: '/test'
    clean: false
    cleanContents: false
    preservePaths: false
    trustSSL: false

  
- task: CmdLine@2
  inputs:
    script: 'app/test.bat'